### ISSUE TITLE
`lineInfo`  in `ErrorBuilder` typeclass does not have access to the line number 

### ISSUE THREAD

**Issue by cybercoder-naj** [j-mie6/gigaparsec#32]
In the current implementation, `lineInfo` has access to the column number, but not the line number.

**Comment by HEIGE-PCloud** [comment]
You can get the position info from [`format`](https://j-mie6.github.io/gigaparsec/Text-Gigaparsec-Errors-ErrorBuilder.html#v:format)

**Comment by j-mie6** [comment]
> You can get the position info from [`format`](https://j-mie6.github.io/gigaparsec/Text-Gigaparsec-Errors-ErrorBuilder.html#v:format)

Yes, but not per line. If you wanted to label the source lines with their numbers, you have to calculate, and that ends up being inaccurate if not all before lines can be sourced

**Comment by j-mie6** [comment]
I think it suffices to just thread in the line number itself into `lineInfo`, I was thinking of calculating all the individual lines so that it receives a `[(Word, String)]`, but this seems to be redundant -- given `line`, you can `zip [line - 1, line - 2 ..] linesBefore` and `zip [line + 1 ..] linesAfter` in `lineInfo` to recover all the information.
